# Generated by Django 4.0.4 on 2022-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=260)),
                ('date', models.DateField()),
            ],
        ),
    ]
